title: fes.ticker::lang.plugin.name
modelClass: Fes\Ticker\Models\Record
list: $/fes/ticker/models/record/columns.yaml
recordUrl: 'fes/ticker/record/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
showSorting: 1
defaultSort:
    column: sort_order
    direction: desc
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
showTree: false
